"""
generate_dress_shared_template.py — one-off script to build the fill-in
scoring sheet for the 15-essay DREsS_New shared subset.

Produces dress_shared_scores_template.csv in the exact long-format schema
classification_model.load_professor_grades() expects: one row per
(essay, criterion, professor), essay_text/question_prompt pre-filled,
criterion_score left blank for the professors' paper scores to be
transcribed in.

Not part of the pipeline itself — run once, then delete or ignore.
"""

import csv

QUESTION_PROMPT = (
    "If you could change one important thing about your university, what "
    "would you change? Give specific reasons and details to support your opinion."
)

ESSAYS = {
    "DRESS-1790": "What I want to change is about COVID-19.\nI think COVID changed most people's daily life, but especially in university.\nFirst, We listen every lecture in Zoom or recorded video, which decrease ability of studying.\nIn this situation, university cannot estimate student ability, so they give S/U or higher grade than past standard.\nIn other university case, student who got lowest score got grade B+, so he feel he don't need to study hard.\nOf course, I never listen lecture in face-to-face, but my brother who has listened lecture in face-to-face has many interconnection with his professor and studies harder than me.\nAlso, by having social distance, we cannot make new social connection, even existing connection.\nFreshmen usually hang out with their new friend in university by having dinner, drinking and playing.\nBut now, We can't stay more than 2 after 6pm, so no time for hanging out.\nAs a result, If I could change one thing, COVID disappear in our life or are ignored in our life.",
    "DRESS-1781": "If I get the huge power to change single important thing in KAIST, I want to change the ABC grade rules to S or U (satisfactory or unsatisfactory) grade rules. I will tell you some reasons why I want to change this rule below.\nFirst, ABC grade policy is very rough to students. Students have to study very hard to get the good grade. For instance, most of the subject related to Math in KAIST is known as 'devil's subject'. Because the content of the subject is about high level math and It follows ABC rules. And also it's name is related to the second reason.\nNext, ABC policy makes forced competition between KAIST members. Math subjects are famous of following the 343 rule strictly which is deviding student into A grade, B grade, C grade by 3:4:3 proportion. So students want to reach 30% of score distribution and they have to compete with each other. It makes another problem. Some could think their friends not companion, but competitor. It will make indivisualism mood on KAIST and let another student to get the thought of competition. Now let's think about 'devil's subject' again. Only few of students attend to Math subject so there are vey high competition mood. It makes student feel tired, too.\nSomeone can say that competiton mood is good for motivating students' learning. But I don't think like that. Most of KAIST students have high motivation to reach their dreams. So, they already wants to study hard. We don't need that mood to pressure and give stressness to KAISTians.\nFinally, It makes teaching assistants also known as TAs feel tired. Because of the grading policy, they have to evaluate students detaily. So they should schedule exams, quizes and make the problems to solve. Except the TA works, TAs are already very busy doing their jobs and It will make them feel tired.\nThese are the reasons why I want to change the ABC grade rules into SU grade rules. I don't know others thought is same as me but I believe that someone who read by writing could change their mind. Thank you for reading my article.",
    "DRESS-1779": "In my university, KASIT, all freshmen have to live in dormitory. There are some dorm policies, but some of them are unacceptable to me and my friends. All my university friends are live in diffenent dormitory bildings. But by the dorm rules, we can't go and play with friends. If we go to others room, we get 50 punish points. If that point goes 100, we get permanant expell.\nI think korean student works hard when they are high school student, so there is no time to high-leveled socialization. University offers student the knowledge about there major, and also in university, student can be socialized by hanging up with friends, or some other people. But in KAIST dorm rule, we cannot do this.\nI think the reason why this rule made is unaccepted people can enter the dormitory and make bad situation and I understand it. But our dorm's security is already high-level. We have to tag our student ID card twice, and press password each room. what a secure. I think this socialization-interupting rule should be delete.\nActually in Yeonsei-university and Kyeongsang National University(KNU) all of students can enter and meet there friends in there room. Almost Korean university student thinks the KAIST student is un-socialized (like a nerd). So I will change this insane rule and make KAISTian happy.\nKAIST says most inportant thing in start-up is currency and they will increase welfare about start-up. But I think most inportant thing in start-up is meet lots of people and get ther opinion and know about demand of people. By deleting this weird rule, more students try to start-up and get more sucess I think.",
    "DRESS-1777": "During your life time, you might have some chance to change system or something else of your surrounding. It can be at your work, family, etc. Making some idea about it will be a nice work for your inhance.\nSince I am spending amount of time in this university, KAIST, I will write about one important-changing-thing about this university. If I have chance to do, I would change the location of university. Some people might say that current location, Daejeon is proper. But my idea is about the specific one.\nI think current location is too far from the main area of the city. For dinner or shopping outside, we have no choice but calling taxi to move to main area. It costs too much money for university students who cannot earn enough money for those things. if KAIST is nearby the center, students could walk around for those things.\nFew disagreement may be caused by the reason of current location. Few decades ago, KAIST positioned here to make Daejeon as the center of science and technology. Following that idea, lots of Labs from government and companies locate near KAIST. It means if we just move only KAIST, communicating with those labs might be hard with the vision of pasts. However, advancement of communication technology could break those worry, so the problem might be nothing.\nThere is one more thing that my friend and I usually talk about. Every system and professors, even environments of KAIST is better than any other university in Korea except only one problem. As you can know, this is the problem about location, which is not in Seoul. Huge amount of infra are concentrated in Seoul, so it is prefered to go university in Seoul. But some problems related to money and laws stop to make new, or move university to Seoul. So moving KAIST near center of Daejeon such as near the train station can be the alternative answer.\nSince problem of capital-concentration of Korea, not all problem of location can be solved with my idea. But with reasons above, I think moving near main area can be alternative answer to clear some issues.",
    "DRESS-1432": "If I could change one thing about KAIST, I would change the location of KAIST to Seoul. There are several reasons that KAIST should move to Seoul.\nFirst, It is hard to communicate with other university in Deajeon. Most of interesting university to KAIST student is located in Seoul, such as Seoul National University, Korea National University, Yeonse Universtiy. But It takes two hours to go to Seoul. Also, There is no interesting place in Deajeon to pull out students from the university.\nSecondly, It is hard to participate in social movement or event. Experience many thing is important. However, most events held in Seoul. Distance between Deajeon and Seoul is too far to participate in events during semester.\nFinally, It is hard to learn other things. In university, student have some time to do non-study-related things. But absoulte number of academies is lower than Seoul. Also, there are not enough people who have same interestings. Another reason is that transportation is so complecate in Deajeon. It makes student to hesitate to go out of the KAIST.\nNon-study-related activities are helpful for creative thinkings. Creative thinkings are very important to do good researches or studies. Therefore non-study-related activities are actually related to study. If KAIST changes location to Seoul, students can get more opportunity to do such things. I suggest that KAIST should move to Seoul.",
    "DRESS-2151": "KAIST should improve KAIMARU\nKAIMARU is the food court in the north of KAIST. There are many dormitories near the KAIMARU, so lots of students eat their meal in KAIMARU. I also live in the north dormitory, so I often go KAIMARU to eat lunch or dinner. However, many students say that KAIMARU need to be improved. And I agree with the students that do not satisfy to KAIMARU with three reasons.\nFirst, KAIMARU is expensive and have bad taste. Of course, KAIMARU is little bit cheaper than other restaurant outside. For example, cafeteria costs 4500 won, so it can be good choice to students. However, some food courts in KAIMARU, they are expensive. Some menus are cost more than 8000 won, so we can not say they are cheap. I think that student restaurant should cheaper than outside restaurant, but some menus in KAIMARU are not. One another problem is those menus are not delicious. It means KAIMARU is not delicious as outside restaurant but expensive as outside restaurant.\nSecond, students have no choice. For students live in the north dormitory, they have no choice for other restaurant. There are Lotteria and Subway, but these are not good for health. When the students want to go restaurant outside the school, they should walk for at least 15 minutes. Lunch time in KAIST is an hour, so they should spend 30 minutes of their lunch time for just walking and I think it is waste of time. However, we can not save our time while we go to KAIMARU. Still many students go to KAIMARU, so they should wait for a long time to eat.\nThird, food courts of KAIMARU do not work on weekend. Therefore, students are hard to have a meal on weekend. They can not cook in dormitory, so they should go outside or eat delivery food. When students go outside, they need to spend lots of time. When students eat delivery food, it is too expensive. Of course the cafeteria in KAIMARU works on weekend but not every time of weekend. I think KAIMARU should work at least Saturday for student.\nTo summarize, KAIST should improve KAIMARU for three reasons. KAIMARU is expensive as other restaurant but not delicious, students have no choice, and KAIMARU do not work on weekend. Having a meal is very important for students. So I think these problems can give lots of stress to students. Therefore, I think KAIST should improve KAIMARU.",
    "DRESS-1450": "Do you remember feeling nervous when you signed up for classes at the begining of the semester? The advantage of university is that we can find and take classes we want, but at the same time it can be a disadvantage. Because other people want to take the class that I want. Most of the classes have more hope than the garden, so some people can't take the classes. Our school selects through a lottery first, the remaining number of people will be selected on a first come, first served. And the cancellation period and application period are divided into night and day. I want to change to eliminate the day and night division of this second draw period and randomly choose the second draw.\nFirst of all, burden of students is reduced. Everyone uses a variety of methods to get on a frist come, first served basis quickly. It is general to use a good computer in a PC room and sometimes use a macro program. Many people gather at once and server is often paralyzed, so you may not be able to use other services. If lottery every day, students will be able to enter the school hompage at their own convenience. Many people around me want this system, too.\nSecondly, it is easier to make a timetable. It is common to chage the timetable to take a class with friend or to see a professer you want. Because the current system is to cancle at night and apply during the day, if you want to change the timetable, you must cancel several classes at once and apply at once. It is almost impossible to change the timetable because it is difficult to win all the class draw. I saw my friends getting a lot of stress from this problem.\nFor these reasons, I hope to freely apply and cancel, and draw classes for one day. Classes in our school are have high quality. Therefore, many students want to take class. But it is impossible for all students to take the classes they want at the time they want, and all students admit it. If the signed up for class system changes as I suggested, I think many Kaistian will be satisfied. I hope everyone can take the class they want next semester.",
    "DRESS-1685": "As COVID-19 spreads out, I had to study in my home for the first semester. It was really hard for me to concentrate to my own study. Since the second semester, I could live in the dormitory. While I live in the dormitory, I felt how comfortable KAIST is to live. So, I am satisfied and accustomed to the system of KAIST. I love everything of KAIST. But there is one thing that I want to improve. That is the wifi system. There are three reasons that I want to change it into much better system.\nFirst, it disconnect itself often. I live in Mir Hall now. But when I went out and come back, my cellphone can find the wifi but have difficulty connecting the wifi. So, I have to wait and use my data until it succeed to connect wifi. The same phenomenon occurs to my iPad, too. It is uncomfortable to use. Even during this post test, the iPad that I joined to the Zoom link was disconnected because the wifi suddenly broke down. So I had to use my hotspot system of my cellphone to connect to the link again.\nSecond, the speed of the wifi system needs to be much faster. I had some experiences about late submission. When I had to submit the assignment rapidly, I could not submit it on time because of the wifi system. I know that I should have taken care of it and submitted it earlier. But if the speed of the wifi system was faster, I could do it on time.\nLastly, there are some places where I can not use wifi. Except for the outside of the buildings like the roads, the sidewalks. I can not use wifi in some places of KAIST. I know that it might be just a dream that can not be realized, but sometimes I feel uncomfortable.\nTo conclude, I felt uncomfortable to use the wifi system of KAIST. Because it disconnect itself randomly, the speed of it is slow, and there are some places that I can not utilize it. If it is improved, I will live and study in KAIST happily. I know that the reasons that I told might not be appropriate to support my opinion. However, that's because I felt really comfortable to use the whole system of KAIST, and it was really hard to find the point to be changed.",
    "DRESS-1778": "If I could change one important thing about my university, I would like to change the way to login the KAIST website. When I just entered KAIST spring semester, I didn't have to login using a smartphone. Only using account ID and password, we could connect the whole KAIST website.\nBut, starting the summer semester, the way to login website has been changed. The new way to login website was this:\n1. Type your KAIST ID.\n2. Connect your KAIST ID and your smartphone using KAIST Auth application.\n3. Everytime you try to login, you must certify twice using your smartphone KAIST Auth app in biological way(finger print or eye information) or OTP(one-time password)\nI always feel uncomfortable when I login KAIST website due to this way to login. This is because I have to turn on my smartphone everytime I login. When I study something I usually turn off my smartphone because that makes me not focused. Also, I have to use KLMS website to study. If I make a mistake to log off KLMS website by turning off the browser or something, I should turn on my smartphone to login again. I think it is such a useless way.\nAlso, there is another problem. If I lost my smartphone or didn't bring it from somewhere, I cannot login to the KAIST website. Because to login always needs a smartphone. It is very important problem to university student, because without KLMS we cannot attend online-classes and that must affect badly to the grade. This situation haven't happened to me yet, but it is enough to occur.\nBut that login way also has benefits. It is safe due to biological data or OTP. So that prevents someone else login to my account. And it does not need account password because biological data and OTP are used like a password.\nHowever, that way has these benefits but I think it is too uncomfortable everytime I login. I wish it changes back to old ways which only need a password of the account and don't need any smartphone application.",
    "DRESS-1449": "I sometimes imagine that I could change something in my university. I know it's hard to change the university, but it will be very nice if I could change something! What would you change if you could change one important thing about your university? In my case, if I could change one important thing about my university, I would remove the test. There are two reasons for my opinion.\nFirst, students can study freely if the tests are removed. There are many things to do, and many students study by force in lack time. If the test is removed, students can study more flexible and they can get more information from increased study time. I thought that the test make students to study before, but when I became a college student, I changed my mind. Students have to study freely. Of course, we can check our knowledge by the test. However, without the test, we can check our knowledge by discussing with other students.\nSecond, many students get stressed about the test. In my case, I got much stress before the test, so I feel like my life is hard to live. However, when there was no test, I didn't feel stressful, and I was happy to study. I think many students don't like to take the exam. Also, when there is no test, students will have more time to relax, and they can develop their hobbies. Therefore, it will make their lives more meaningful.\nTo sum up, students can study freely if the tests are removed and many students get stressed about the test, so I would remove the test and increase discussing time with other students. Also, I think it will be better if we can do some project in 1st grade in KAIST, and make something special. We can do that later now, but I think change the test to project will be better. but, there is one thing the most important. Students have to study hard although the tests are removed.",
    "DRESS-1412": "KAIST, our university, has many differences from other universities. First of all, KAIST is the Institute of Science and Technology, with only departments with natural science and engineering. There are many departments in KAIST such as mathematics, electrical engineering, computer science, physics, and more. Freshmen in KAIST go to School of Freshmen which they can study basic subjects of mathematics, physics, chemistry, biology, and programming. Students in KAIST choose their major subject as they go to second grade. The purpose of the School of Freshmen is to give opportunity to explore many subjects. I think this is the biggest difference compared to other universities. In spite of School of Freshmen provides opportunity of exploring many subjects to students, I think there are more disadvantages of School of Freshmen. If I could change one important thing about KAIST, I would like to change the system of School of Freshmen.\nFirst, there are many students who have already decided their major subject. In my case, I am interested in computer science, so I have decided to go to School of Computing even before the admission. I think some basic subjects such as mathematics and English are essential for all majors, but some subjects such as physics, chemistry, and biology might not be helpful unless the student choose the related major. It might be a waste of time to students who have already decided the major. Furthermore, these students would like to study more about subjects they are interested in. Basic subjects which are mandatory might make students harder to study their interested subjects.\nSecond, taking all classes of basic subjects might cause bad effects on student's grade. Every student has their own subject of confidence. Some student might have talent in mathematics, but the student might be poor in other subjects such as chemistry. In my case, I am confident with subjects of programming, but I am not good at chemistry. The system about learning all basic subjects might make student's grade lower.\nFinally, systems in School of Freshmen is not the only way to explore many majors. The main purpose of School of Freshmen is to explore many majors and to help students choose their major. However, studying all basic subject might make the students lose their interest. There are department briefing session which students can get information about the major. I think the department briefing session is more beneficial for students to choose their major.\nIn conclusion, for these reasons, I think there are more disadvantages of system in School of Freshmen. So I would like to change the system about School of Freshmen. Having many department briefing sessions earlier might solve this problem.",
    "DRESS-1664": "When I first saw inside of the KAIST, the most impressive thing except something related with study or research was Ryu Keunchul Sports Complex. In there, people did many sports like basketball. For me who like basketball, It was amazing feeling by its massive size, good state, and variable use. But by COVID-19, Sports Complex has been closed or limited to use since early 2020. Now I think it is time to remove the limitation for use of Sports Complex. KAIST student should use that place freely. Let me tell you the reason.\nFirst, we should think the student's right. For students who like to plat sports, they will want to use Sports Complex, but they cannot use freely because university blocked it. This situation is the case student's right is not considered. They should have the right to use the place in KAIST freely as KAIST students.\nSecond, students is getting tired. When I was in school at January 2020 by some class, after a series of hard classes, I get rid of my stress from playing basketball at night. Also the research says playing sports is helpful for not only our physical health but also our psychological health by expose of some hormones which affect people to feel happy. Like this, playing sports is funny thing and the way to remove stresses. But now, students feel hard to find some place to play sports, then this can lead to depression and getting tired.\nIn conclusion, Sports complex which has massive size should be opened now. I think these negative affects is bigger than the positive things by limitation. Of course preventing spread of virus is important, but if limitation is too long, students' life is too tired and depressed. If we prevent to use of people who is not related with KAIST and manage the place, for example, cleaning and tak very well, we can avoid some bad situation by COVID-19. It is time to change.",
    "DRESS-1652": "I'm a student of KAIST. KAIST is such a good university in Korea. A lot of Korean students want to go there. KAIST has great education systems and great campus. However, I am not fully satisfying with my university. I want to change a lot of things in my university. If I could change one important thing about my university, I would change every cafeterias and restaurants in campus.\nI love to eat something. In usual, male students do not have a big interest in food. However, I am really interested in it and I know well about foods and restaurants than usual female students. That is why I want to change the total cafeterias and restaurants. First, I want make menus of cafeteria more various. I love to try new menus and new restaurants. I do not like going same restaurant everyday, but in university, it is not easy. Many students go cafeteria to eat breakfast, lunch, and dinner. When we go outside of university and eat food for everyday, it spends a lot money and time. College students' most valuable thing is money and time, so we have to eat food in campus a lot. In reality, we go same cafeteria called Kai Maru everyday, because different cafeteria is too far from dormitory. However, there are just few kinds of menus in Kai Maru. It needs just 3 days to get bored about same menu. Next, we need more cafeterias. In our college, there are just few cafeterias, so students are crowded in cafeterias in every lunch and dinner time. We need to wait for eat food and the average waiting time is almost 20 minutes. However, some day we have only 30 minutes to eat lunch. We have to eat really fast or can not eat at all. Last, foods need to be healthier and more delicious. Kai Maru's food is famous for awful taste. Except few menus, taste of menus are too strong and not good at all. I think cafeteria needs to provide more healthier food, not using instant foods and too spicy and salty foods.\nIf there are real change in the food and cafeteria, many students will be happy and do not get stressed about foods. It can even affect to study I think. This will give a big change in our campus life.",
    "DRESS-1433": "University students encounter many problems and stress. The best thing that make most students relax and enjoy is food. However, students also have problems during their meals. Have you ever experienced a crowd of people during lunch time in school or university? Have you ever been upset with that situation? I am the one who had encountered this problem since primary school until university. Therefore, if I could change one crucial thing about my university, I would like to make a change in cafeteria with these three aspects.\nFirst of all, an increase in cafeteria's capacity is important. During lunch time, crowded students need to have lunch at the same time, so the quantity and size of the cafeterias are not enough for a large number of students. I think if the university could build a new cafeteria at the place near the East cafeteria, students would be more comfortable for their lunch.\nFurthermore, the food selling time is fixed, so the students who finish the class early connot get their food before the selling time. They have to wait until that time. This also brings about crowded people in the cafeteria. If those students who finish the class early could have their lunch before other students, there would be less crowd during lunch time in the cafeteria, and they would not have to waste their time waiting for the selling period. Hence, the food selling period should be more flexible.\nFinally, I would like to add a new rule for using cafeteria during lunch time. Sometimes, students who had already finished their lunch do not give their seats to other students who haven't had their meals yet. Those students continue to talk to their friends after finishing their lunch, so other students do not have a seat. This behavior should be prohibited during rush hour such as lunch time, and the rule should be set.\nIn conclusion, the problems about the university cafeteria should be solved. If I could make some changes in my university cafeteria, I would like to change in its capacity, and make the food selling time more flexible. Moreover, the rule for using cafeteria should be set for students to give their seats to other students who haven't had their meals. I think if the university cafeteria could be changed in these ways, students would feel better about their lunch and have more time left to do other activities during their break time.",
    "DRESS-2193": "Many college students have the wrong life pattern. They sleep late in the night and wake up late in the afternoon. If I can change my only one thing, I will change my life pattern like it for the folowing reasons.\nFirst, if I can wake up early in the mornig, I can eat breakfast. Beause I wake up late, I cannot eat breakfast, and I have no choice but to go to class hungry. Getting up early solves this problem.\nSecond, I can do morning exercise. In the morning, I am still tired, but I can start my day refreshing by exercise. In addition, if I exercise early in the morning, I can exercise again at night.\nThird, I can save my money. If I stay up late at night, I have to relay on delivery because university restaurants are close. Delivery food is quite expensive, so I can save my money just by not eating it.\nLastly, I can see the sunlight much more. When I sleep alte at night and wake up late in the afternoon, I can see the sunlight only in a short time of the day. More sunlight makes I feel better and healthier.\nChanging the life pattern looks easy, but it does not. Through this vacation, I will try to change my life pattern. I think it would be nice if you could join me. Thank you for reading.",
}

CRITERIA = ["Content", "Organization", "Language"]
CRITERION_MAX_POINTS = 5
PROFESSORS = ["profA", "profB", "profC", "profD", "profE"]

OUT_PATH = "classification_model/dress_shared_scores_template.csv"


def main():
    with open(OUT_PATH, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow([
            "essay_id", "part", "professor_id", "question_prompt", "essay_text",
            "criterion_name", "criterion_max_points", "criterion_score",
        ])
        for essay_id, essay_text in ESSAYS.items():
            for professor_id in PROFESSORS:
                for criterion_name in CRITERIA:
                    writer.writerow([
                        essay_id, 2, professor_id, QUESTION_PROMPT, essay_text,
                        criterion_name, CRITERION_MAX_POINTS, "",
                    ])
    print(f"Wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
